app/models.py
import uuid
from datetime import datetime
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, String, Boolean, DateTime


Base = declarative_base()


class Applicant(Base):
    '''Model for applicants'''
    __tablename__ = "applicants"

    id = Column(String(255), primary_key=True, default=uuid.uuid4, unique=True, nullable=False)
    applicant_fullname = Column(String(255), nullable=False)
    applicant_email = Column(String(255), nullable=False)
    applicant_phone = Column(String(255), nullable=False)
    applicant_address = Column(String(255), nullable=False)
    applicant_location = Column(String(255), nullable=False)
    applicant_employment_status = Column(String(255), nullable=False)
    purpose_loan = Column(String(255), nullable=False)
    amount = Column(String(255), nullable=False)
    guanrantor_fullname = Column(String(255), nullable=False)
    guanrantor_email = Column(String(255), nullable=False)
    guanrantor_phone = Column(String(255), nullable=False)
    guanrantor_address = Column(String(255), nullable=False)
    guarantor_relationship_to_applicant = Column(String(255), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __init__(self, applicant_fullname, applicant_email, applicant_phone,
                 applicant_address, applicant_location, applicant_employment_status,
                 purpose_loan, amount, guanrantor_fullname, guanrantor_email, guanrantor_phone,
                 guanrantor_address, guarantor_relationship_to_applicant):
        self.applicant_fullname = applicant_fullname
        self.applicant_email = applicant_email
        self.applicant_phone = applicant_phone
        self.applicant_address = applicant_address
        self.applicant_location = applicant_location
        self.applicant_employment_status = applicant_employment_status
        self.purpose_loan = purpose_loan
        self.amount = amount
        self.guanrantor_fullname = guanrantor_fullname
        self.guanrantor_email = guanrantor_email
        self.guanrantor_phone = guanrantor_phone
        self.guanrantor_address = guanrantor_address
        self.guarantor_relationship_to_applicant = guarantor_relationship_to_applicant

    def __str__(self):
        return f'<Applicant {self.id} {self.applicant_fullname}>'

    def __repr__(self):
        return f'''Applicant(id={self.id}, applicant_fullname={self.applicant_fullname},
    applicant_email={self.applicant_email}, applicant_phone={self.applicant_phone},
    applicant_address={self.applicant_address}, applicant_location={self.applicant_location},
    applicant_employment_status={self.applicant_employment_status}, purpose_loan={self.purpose_loan},
    amount={self.amount}, guanrantor_fullname={self.guanrantor_fullname}, guanrantor_email={self.guanrantor_email},
    guanrantor_phone={self.guanrantor_phone}, guanrantor_address={self.guanrantor_address},
    guarantor_relationship_to_applicant={self.guarantor_relationship_to_applicant})'''

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Email


class ApplicantForm(FlaskForm):
    '''Applicant Form'''
    applicant_fullname = StringField('Full Name', render_kw={"placeholder": "Enter your full name"}, validators=[DataRequired()])
    applicant_email = StringField('Email', render_kw={"placeholder": "Enter your email"}, validators=[DataRequired(), Email()])
    applicant_phone = StringField('Phone Number', render_kw={"placeholder": "Enter your phone number"}, validators=[DataRequired()])
    applicant_address = StringField('Address', render_kw={"placeholder": "Enter your address"}, validators=[DataRequired()])
    applicant_location = StringField('Location', render_kw={"placeholder": "Enter your location"}, validators=[DataRequired()])
    applicant_employment_status = StringField('Employment Status', render_kw={"placeholder": "Enter your employment status"}, validators=[DataRequired()])
    purpose_loan = StringField('Loan Purpose', render_kw={"placeholder": "Enter the purpose of the loan"}, validators=[DataRequired()])
    amount = StringField('Loan Amount', render_kw={"placeholder": "Enter the loan amount"}, validators=[DataRequired()])
    guanrantor_fullname = StringField('Guarantor Full Name', render_kw={"placeholder": "Enter the guarantor's full name"}, validators=[DataRequired()])
    guanrantor_email = StringField('Guarantor Email', render_kw={"placeholder": "Enter the guarantor's email"}, validators=[DataRequired(), Email()])
    guanrantor_phone = StringField('Guarantor Phone Number', render_kw={"placeholder": "Enter the guarantor's phone number"}, validators=[DataRequired()])
    guanrantor_address = StringField('Guarantor Address', render_kw={"placeholder": "Enter the guarantor's address"}, validators=[DataRequired()])
    guarantor_relationship_to_applicant = StringField('Guarantor Relationship to Applicant', render_kw={"placeholder": "Enter the guarantor's relationship to the applicant"}, validators=[DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
import os
from dotenv import load_dotenv
from flask import Flask
from .models import Base
from .db import init_db

load_dotenv()


init_db(Base)

app = Flask(__name__)

app.config['SECRET_KEY'] = os.getenv('SECRET_KEY')

from .routes import bp

app.register_blueprint(bp)

app/routes.py
from flask import Blueprint, render_template, request, flash, url_for, redirect
from .forms import ApplicantForm
from .db import session
from .models import Applicant


bp = Blueprint('index', __name__)


@bp.route('/', methods=['GET'], strict_slashes=True)
def index():
    return render_template('index.html')


@bp.route('/request-loan', methods=['GET'], strict_slashes=True)
def request_loan_form():
    form = ApplicantForm()
    return render_template('loan.html', form=form)


@bp.route('/request-loan', methods=['POST'], strict_slashes=True)
def request_loan():
    s = session()
    request_data = request.form.to_dict()
    form = ApplicantForm(**request_data)

    if form.validate_on_submit():
        del request_data['csrf_token']
        del request_data['submit']

        new_applicant = Applicant(**request_data)

        s.add(new_applicant)
        s.commit()
        flash(message='Request added successfully!', category='success')
        return redirect(url_for('index.index'))
    flash(message='Please check your form again.', category='error')
    return redirect(url_for('index.request_loan_form'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/reset.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/index.css') }}">
    {% block styles %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <!-- header -->
    <header>
        <div class="container">
            <h1>
                Loan<span class="highlight">Hub</span>
            </h1>
            <nav>
                <ul>
                    <li>
                        <a href="{{ url_for('index.request_loan_form') }}">Request Loan</a>
                    </li>
                </ul>
            </nav>
        </div>
    </header>
    {% block content %}{% endblock %}
    <footer>
        <div class="container">
            <h3>Loan<span>Hub</span></h3>
            <p>&copy; Copyright 2023 all rights reserved.</p>            
        </div>
    </footer>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block title %}LoanHub{% endblock %}

{% block content %}

    <!-- main -->
    <main>
        <section id="hero">
            <section id="flash-messages">
                {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                    <div class="container">
                        <div class="{{ category }}">
                            {{ message }}
                        </div>
                    </div>
                    {% endfor %}
                {% endif %}
                {% endwith %}
            </section>
            <div class="container">
                <p>
                    Welcome to LoanHub, where your dreams find the support they need to thrive. Our seamless loan application process is designed with your convenience in mind. Let us help you achieve your goals and aspirations with our flexible and tailored loan options. Take the first step towards a brighter future today!
                </p>
                <a href="{{ url_for('index.request_loan_form') }}">Apply for a loan</a>
            </div>
        </section>
        <section id="feature">
            <div class="container">
                <h2>Feature</h2>
                <hr>
                <p>
                    At LoanHub, we've designed our platform to provide you with the best possible experience when it comes to securing the financial support you need. Here are some of the key features that make LoanHub stand out:
                </p>
                    <ul>
                        <li>
                            User-Friendly Interface: Our website is intuitively designed, making it easy for you to navigate, explore loan options, and complete your application hassle-free.
                        </li>
                        <li>
                            Loan Options for Every Need: Whether you're looking for a personal loan, a business loan, or a specialized loan product, LoanHub offers a wide range of loan options to cater to your specific financial requirements.
                        </li>
                    </ul>
            </div>
        </section>
        <section id="about">
            <div class="container">
                <h2>About Us</h2>
                <p>
                    At LoanHub, we're on a mission to empower your financial dreams. We understand that life is full of opportunities and challenges, and sometimes, you need a helping hand to seize those opportunities or overcome those challenges. That's where we come in.
                </p>
                <p>
                    We're not just another loan service; we're your financial partner. We're committed to making the lending process straightforward, accessible, and transparent. We believe everyone deserves a fair shot at achieving their goals, and that's why we offer a range of loan options to suit your unique needs and circumstances.
                </p>
            </div>
        </section>
    </main>
{% endblock %}

app/templates/loan.html
{% extends 'base.html' %}

{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/loan.css') }}">
{% endblock %}

{% block title %}Request Loan{% endblock %}

{% block content %}
    <section id="loan">
        <section id="flash-messages">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                <div class="container">
                    <div class="{{ category }}">
                        {{ message }}
                    </div>
                </div>
                {% endfor %}
            {% endif %}
            {% endwith %}
        </section>
        <div class="container">
            <div>
                <h2>Request Loan Form</h2>
                <p>Fill the form below to request for a loan.</p>                    
            </div>
            <form action="{{ url_for('index.request_loan') }}" method="post">
                {{ form.csrf_token }}
                <div class="form-field">
                    {{ form.applicant_fullname.label }}
                    {{ form.applicant_fullname }}
                </div>
                <div class="form-field">
                    {{ form.applicant_email.label }}
                    {{ form.applicant_email }}
                </div>
                <div class="form-field">
                    {{ form.applicant_phone.label }}
                    {{ form.applicant_phone }}
                </div>
                <div class="form-field">
                    {{ form.applicant_address.label }}
                    {{ form.applicant_address }}
                </div>
                <div class="form-field">
                    {{ form.applicant_location.label }}
                    {{ form.applicant_location }}
                </div>
                <div class="form-field">
                    {{ form.applicant_employment_status.label }}
                    {{ form.applicant_employment_status }}
                </div>
                <div class="form-field">
                    {{ form.purpose_loan.label }}
                    {{ form.purpose_loan }}
                </div>
                <div class="form-field">
                    {{ form.amount.label }}
                    {{ form.amount }}
                </div>
                
                <h3>Guarantor Information</h3>
                <div class="form-field">
                    {{ form.guanrantor_fullname.label }}
                    {{ form.guanrantor_fullname }}
                </div>
                <div class="form-field">
                    {{ form.guanrantor_email.label }}
                    {{ form.guanrantor_email }}
                </div>
                <div class="form-field">
                    {{ form.guanrantor_phone.label }}
                    {{ form.guanrantor_phone }}
                </div>
                <div class="form-field">
                    {{ form.guanrantor_address.label }}
                    {{ form.guanrantor_address }}
                </div>
                <div class="form-field">
                    {{ form.guarantor_relationship_to_applicant.label }}
                    {{ form.guarantor_relationship_to_applicant }}
                </div>
                {{ form.submit(class="btn") }}
            </form>
        </div>
    </section>
{% endblock %}